import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '../components/layout/Header'
import SideMenu from '../components/layout/SideMenu'
import LeftSidebar from '../components/layout/LeftSidebar'
import RightSidebar from '../components/layout/RightSidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className + ' ' + 'dark:bg-gray-950 bg-gray-100 antialiased'}>
        <Header />
        <LeftSidebar />
        <RightSidebar />
        {children}
      </body>
    </html>
  )
}
