import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "../components/layout/Header";
import SidebarLeft from "../components/layout/SidebarLeft";
import SidebarRight from "../components/layout/SidebarRight";
import Button from "../components/Button";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='dark'>
      <body
        className={
          inter.className + " " + "dark:bg-gray-950 bg-gray-200 antialiased"
        }
      >
        <Header />
        <SidebarLeft />
        <SidebarRight />

        {children}
      </body>
    </html>
  );
}
